-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT AO.ANIMAL_ID, AO.NAME, (AO.DATETIME - AI.DATETIME) AS "DURATION"
FROM ANIMAL_OUTS AS AO
LEFT JOIN ANIMAL_INS AS AI
USING(ANIMAL_ID)
WHERE AI.ANIMAL_ID IS NOT NULL
ORDER BY DURATION DESC
LIMIT 2) AS ANSWER;

-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AS AO
LEFT JOIN ANIMAL_INS AS AI
USING(ANIMAL_ID)
ORDER BY AO.DATETIME - AI.DATETIME DESC
LIMIT 2;