WITH RECURSIVE DUMMY_HOUR_TABLE AS
(SELECT 0 AS HOUR
UNION ALL
SELECT HOUR+1
FROM DUMMY_HOUR_TABLE
WHERE HOUR < 23)                
SELECT DUMMY_HOUR_TABLE.HOUR, COUNT(HOUR(ANIMAL_OUTS.DATETIME)) AS "COUNT"
FROM DUMMY_HOUR_TABLE
LEFT JOIN ANIMAL_OUTS
ON DUMMY_HOUR_TABLE.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY DUMMY_HOUR_TABLE.HOUR
ORDER BY DUMMY_HOUR_TABLE.HOUR;